# Generated by Django 3.2.12 on 2022-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mylist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('fueltype', models.CharField(max_length=200)),
                ('tax', models.CharField(max_length=200)),
                ('mpg', models.CharField(max_length=200)),
                ('enginesize', models.CharField(max_length=200)),
            ],
        ),
    ]
