# Generated by Django 3.2.12 on 2022-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mylist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
