# Generated by Django 3.2.12 on 2022-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mylist_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='company',
            field=models.CharField(max_length=200),
        ),
    ]
